title: \PowerShell Escape
description: "a blog about Powershell, DevOps, and all things IT. \r\n homepage of Matt McNabb"
BASE_PATH:
permalink: :title
paginate: 6
paginate_path: "page:num"
disqus: mattmcnabbgithubio
google_analytics: UA-69802890-1
rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
resources_path: resources.html

highlighter: rouge
markdown: kramdown

author:
  name: Matt McNabb
  email: mmcnabb@outlook.com
  github: mattmcnabb
  twitter: mcnabbmh
  bio: Windows Systems Engineer and PowerShell enthusiast | 2016 PowerShell.org PowerShell Hero
  email_md5: 726351295ec82e145928582f595aa3aa
  image: /assets/media/MattBW.png

# set it as url of an image
sidebar_logo: /assets/media/PowerShellHero150x150.png

exclude: ["README.md","jekyll-metadata"]
gems:
  - jekyll-paginate
  - jekyll-gist
